name: "Reusable Setup"
description: "Checks out code, sets up BATS, and substitutes version."

inputs:
  os:
    description: "The OS of the runner (ubuntu-latest, macOS-latest, windows-latest)"
    required: true
  setup-bats:
    description: "Whether to set up BATS"
    required: false
    default: "false"

outputs:
  bats-lib-path:
    description: "Path to BATS libraries if setup-bats was true"
    value: ${{ steps.set-bats-paths.outputs.lib-path }}

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      with:
        fetch-depth: 0
        persist-credentials: false

    # --- BATS INSTALLATION ---
    - name: Install BATS Core (Linux)
      if: ${{ inputs.setup-bats == 'true' && startsWith(inputs.os, 'ubuntu') }}
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y bats
        sudo apt-get upgrade -y

    - name: Install BATS Core (macOS)
      if: ${{ inputs.setup-bats == 'true' && startsWith(inputs.os, 'macOS') }}
      shell: bash
      run: |
        brew install bats-core
        brew update && brew upgrade

    - name: Install BATS Helper Libraries
      if: ${{ inputs.setup-bats == 'true' }}
      shell: bash
      run: |
        echo "Cloning BATS helper libraries..."
        # Clone into the paths defined in your original action file
        git clone --depth 1 https://github.com/bats-core/bats-support.git "${{ github.workspace }}/tests/bats-support"
        git clone --depth 1 https://github.com/bats-core/bats-assert.git "${{ github.workspace }}/tests/bats-assert"
        git clone --depth 1 https://github.com/bats-core/bats-file.git   "${{ github.workspace }}/tests/bats-file"
        echo "Helper libraries installed."

    - name: Set BATS Library Path Output
      # This step manually constructs the output path that bats-action *would have*
      if: ${{ inputs.setup-bats == 'true' }}
      id: set-bats-paths
      shell: bash
      run: |
        BATS_SUPPORT_PATH="${{ github.workspace }}/tests/bats-support"
        BATS_ASSERT_PATH="${{ github.workspace }}/tests/bats-assert"
        BATS_FILE_PATH="${{ github.workspace }}/tests/bats-file"

        # This is the colon-separated path the action was supposed to output
        LIB_PATH="${BATS_SUPPORT_PATH}:${BATS_ASSERT_PATH}:${BATS_FILE_PATH}"

        echo "BATS lib-path manually set to: $LIB_PATH"
        echo "lib-path=$LIB_PATH" >> $GITHUB_OUTPUT
    # --- END BATS SETUP ---
    # --- KCOV INSTALL (with caching) ---
    - name: Cache kcov
      if: ${{ inputs.setup-bats == 'true' && startsWith(inputs.os, 'ubuntu') }}
      id: cache-kcov
      uses: actions/cache@v4
      with:
        # Cache the installation directory
        path: ~/kcov-installed
        # A simple key, will rebuild if runner image changes
        key: kcov-build-v1-${{ runner.os }}

    - name: Install kcov (build from source for Linux)
      if: ${{ inputs.setup-bats == 'true' && startsWith(inputs.os, 'ubuntu') && steps.cache-kcov.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        echo "Installing kcov dependencies..."
        sudo apt-get update
        sudo apt-get install -y build-essential cmake pkg-config \
                                  libcurl4-openssl-dev libelf-dev libdw-dev \
                                  binutils-dev libiberty-dev

        echo "Cloning and building kcov..."
        git clone --depth 1 https://github.com/SimonKagstrom/kcov.git
        cd kcov
        mkdir build
        cd build
        # Install to a local, cacheable directory
        cmake .. -DCMAKE_INSTALL_PREFIX=~/kcov-installed
        make
        make install
        echo "kcov installed to ~/kcov-installed"

    - name: Add kcov to PATH
      if: ${{ inputs.setup-bats == 'true' && startsWith(inputs.os, 'ubuntu') }}
      shell: bash
      run: |
        echo "$HOME/kcov-installed/bin" >> $GITHUB_PATH
        echo "kcov path added. Location: $(command -v kcov)"
    # --- END KCOV INSTALL ---
    - name: Substitute Version Number into gitwatch.sh
      shell: bash
      run: |
        VERSION_NUMBER=$(cat VERSION)
        # Handle macOS sed -i incompatibility
        if [ "${{ inputs.os }}" == "macOS-latest" ]; then
          sed -i '' "s/%%GITWATCH_VERSION%%/${VERSION_NUMBER}/g" gitwatch.sh
        else
          sed -i "s/%%GITWATCH_VERSION%%/${VERSION_NUMBER}/g" gitwatch.sh
        fi
        echo "Substituted version ${VERSION_NUMBER} into gitwatch.sh for testing."
