name: "Reusable Setup"
description: "Checks out code, sets up BATS, and substitutes version."

inputs:
  os:
    description: "The OS of the runner (ubuntu-latest, macOS-latest, windows-latest)"
    required: true
  setup-bats:
    description: "Whether to set up BATS"
    required: false
    default: "false"

outputs:
  bats-lib-path:
    description: "Path to BATS libraries if setup-bats was true"
    value: ${{ steps.setup-bats.outputs.lib-path }}

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Setup BATS and Libraries
      # Note: Composite action inputs are always strings, so we check for 'true'
      if: ${{ inputs.setup-bats == 'true' }}
      id: setup-bats
      uses: bats-core/bats-action@v2 # <-- Changed to the major version tag
      with:
        support-path: "${{ github.workspace }}/tests/bats-support"
        assert-path: "${{ github.workspace }}/tests/bats-assert"
        file-path: "${{ github.workspace }}/tests/bats-file"
        detik-install: "false"

    - name: Substitute Version Number into gitwatch.sh
      shell: bash
      run: |
        VERSION_NUMBER=$(cat VERSION)
        # Handle macOS sed -i incompatibility
        if [ "${{ inputs.os }}" == "macOS-latest" ]; then
          sed -i '' "s/%%GITWATCH_VERSION%%/${VERSION_NUMBER}/g" gitwatch.sh
        else
          sed -i "s/%%GITWATCH_VERSION%%/${VERSION_NUMBER}/g" gitwatch.sh
        fi
        echo "Substituted version ${VERSION_NUMBER} into gitwatch.sh for testing."
