---
# Linter rules doc:
# - https://github.com/DavidAnson/markdownlint
#
# This file is based off of the github action super-linter template:
# - https://github.com/github/super-linter/blob/master/TEMPLATES/.markdown-lint.yml
#
# Note:
# To comment out a single error:
#   <!-- markdownlint-disable -->
#   any violations you want
#   <!-- markdownlint-restore -->

# Default state for all rules
default: true

# --- Rules to Disable ---
# MD004: Unordered list style
MD004: false
# MD033: Inline HTML
MD033: false
# MD024: Allow duplicate headings (for CHANGELOG.md)
MD024: false

# --- Rules to Configure ---
# MD007: Set unordered list indentation to 2 spaces
MD007:
  indent: 2

# MD013: Set line length to 90 (matches .editorconfig)
# and disable line length checks for tables (for README.md)
MD013:
  line_length: 90
  tables: false

# MD049: Set emphasis style to UNDERSCORE (to match Prettier/existing files)
MD049:
  style: underscore
