name: Docker Build and Publish

# Allows you to run this workflow manually from the Actions tab
on: workflow_dispatch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        # This new step generates tags based on the branch
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            # 1. Tag with the git SHA (e.g., f4be4d7) on all builds
            type=sha
            
            # 2. Tag 'latest' IF the build is from the 'master' branch
            type=ref,event=branch,pattern=master,value=latest
            
            # 3. Tag with the sanitized branch name (e.g., 'my-feature')
            #    IF the build is NOT from the 'master' branch.
            type=ref,event=branch,pattern={{sanitize}},enable_if=ne=refs/heads/master

      - name: Build and push Docker image
        # This step is updated to use the tags from the 'meta' step
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Use the tags and labels generated by the metadata action
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
